<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Monday 8th of September 2014 08:43:35 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://bookmart.herokuapp.com/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "128873310281-ev4bn0ur96ujqpvf9s48gv5uqqin6l02.apps.googleusercontent.com", "secret" => "bHPiEoaCsLcqxNMfuobekW_u" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1460835000856920", "secret" => "6f4468983c570e4b38a97fec85eb70a3" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "XmfRVeWAOeISDVkdMOPepTTd2", "secret" => "MZqT9cDt8xo920Yhh1Hmdki7KdtzjqLhR0jGUbPDCjdaEkVKoG" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
